---
apiVersion: v1
kind: Service
metadata:
  name: app-task1
spec:
  selector:
    app: app1
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: multitool-http
      protocol: TCP
      port: 1180
      targetPort: 1180
    - name: multitool-https
      protocol: TCP
      port: 11443
      targetPort: 11443
...