apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-mt
spec:
  ports:
    - name: nginx
      port: 9001
      targetPort: 80
    - name: multitool
      port: 9002
      targetPort: 8080
  selector:
    app: my-app
